[project]
name = "backend-geotrainpoly"
version = "0.1.0"
description = "COSCUP 2025 大地遊戲後端服務"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "python-dotenv>=1.1.0",
    "uvicorn>=0.34.3",
]
